# Generated by Django 3.2.9 on 2021-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='ProductID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CateID',
            new_name='Cate',
        ),
    ]
