# Generated by Django 3.2.9 on 2021-12-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211221_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ImgPath',
            field=models.CharField(max_length=500),
        ),
    ]
