# Generated by Django 3.2.9 on 2021-12-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211221_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='User',
        ),
    ]
