# Generated by Django 3.2.9 on 2021-12-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_customer_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Customer',
            new_name='UserID',
        ),
        migrations.RenameField(
            model_name='cartdetail',
            old_name='Product',
            new_name='ProductID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='UserID',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Order',
            new_name='OrderID',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Product',
            new_name='ProductID',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Cate',
            new_name='CateID',
        ),
    ]
