# Generated by Django 3.2.9 on 2021-12-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211221_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='UserID',
        ),
        migrations.AddField(
            model_name='cart',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
