# Generated by Django 3.2.9 on 2021-12-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211221_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
