# Generated by Django 3.2.9 on 2021-12-20 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Username',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
