# Generated by Django 3.2.9 on 2021-12-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211221_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CateID',
            new_name='Cate',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='UnitPrice',
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
