# Generated by Django 3.2.9 on 2021-12-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211221_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Cate',
            new_name='CateID',
        ),
    ]
